### ISSUE TITLE
Add more than one website to netzwerk detail page

### ISSUE THREAD

**Issue by GuidaGG** [GuidaGG/NZN-frontend#116]
- make possible to add more:
  - separate by coma
- enforce https:// if people dont add it

- 4. If I click on the link in the profile of “Network Future Places”.
If I click on their website, I will only ever go to the same page
profile again. The same is also the case with the competence team
Munich and a few others, but not all. Sometimes
It's also the case that I can no longer close the profile.

**Comment by ah-bas-und-aer** [comment]
Is that the issue with the hyperlink which always directs to the same page?
