### ISSUE TITLE
Desktop Header

### ISSUE THREAD

**Issue by ah-bas-und-aer** [GuidaGG/NZN-frontend#118]
- Logo row: more spacing between AAA and SBMS; align logos to the upper corner of the NZN 
- Align „Anmeldung zum Netzwerk“ moroe the the left corner of the bottons than to their texts.

**Comment by GuidaGG** [comment]
Logo row: more spacing between AAA and SBMS; align logos to the upper corner of the NZN
- the logos need to have all the same spacing around, which is not the case. Some have more space on top than others.

**Comment by ah-bas-und-aer** [comment]
> Logo row: more spacing between AAA and SBMS; align logos to the upper corner of the NZN
> 
>     * the logos need to have all the same spacing around, which is not the case. Some have more space on top than others.

I add similar whitespace around each logo, you'll find it in GoogleDrive/GenerellesMaterial/ExterneLogos
