### ISSUE TITLE
Desktop Netzwerk

### ISSUE THREAD

**Issue by ah-bas-und-aer** [GuidaGG/NZN-frontend#120]
- Intro text: Still in the bigger font size
- Add placeholder fot profiles that do not have a photo (I create one for you)
- Sometimes on profile images heads are cropped, how to deal with that? (Freiraumbüro_blau, die Urbanisten)
- Sidebar: spacing between X-field and definition smaller
- will there still be category devisions such as in the screendesigns (f.i. A:.... B...... C.... )
! Zirkulaar: Link is not correct
! Hyperlinks should be opened in a nex tab
! Can you explain why do you decided the following: by clicking on one profile it moves out of the sidebar, isn't that rather confusing?

**Comment by GuidaGG** [comment]
! Zirkulaar: Link is not correct
- implement validation for links on form and add placeholder
- extra: add more than one link with comma

**Comment by GuidaGG** [comment]
! Can you explain why do you decided the following: by clicking on one profile it moves out of the sidebar, isn't that rather confusing?

- it doesnt move move out of the sidebar. Its because the default seleciton is random, so whenever you reload the page the sidebar elements are re randomized. IF you order it by A-Z, this doesnt happen.

I talked with Svenja about this and she liked the function like this.

**Comment by GuidaGG** [comment]
- Sometimes on profile images heads are cropped, how to deal with that? (Freiraumbüro_blau, die Urbanisten)
- see #94 
- remove min-height from image and add it to container aswell as overflow-hidden
- get priotiry field from backend - object-top, object-center, object-bottom

**Comment by GuidaGG** [comment]
from svenja
-5. The profiles do not show in which areas the
Partners can offer help and where they need help. That should still be the case
be added and it would also be cool if the city was there.

**Comment by GuidaGG** [comment]
from svenja
-6. On the map I think it would be cool if you go to the pins
the partner's name may be displayed. Would that still be possible?
program or would that be too complicated?

**Comment by ah-bas-und-aer** [comment]
> * will there still be category devisions such as in the screendesigns (f.i. A:.... B...... C.... )
>       Probably we cant make this.

okay

**Comment by ah-bas-und-aer** [comment]
> * Intro text: Still in the bigger font size
Still bigger font

**Comment by ah-bas-und-aer** [comment]
> Sidebar: spacing between X-field and definition smaller
Do you understand the correction? The name of the sort option should be clearer assigned to the check box
