### ISSUE TITLE
Astrids graphics

### ISSUE THREAD

**Issue by ah-bas-und-aer** [GuidaGG/NZN-frontend#130]
@farzadgo  I added graphics for network thumbnails to the google drive/gerneal material/NZN Grafik Background. It is available in serveral file formats. The graphic strokes might also be added by coding? See what you can use. it should also be the header image for a profile page without photos.

(For thumbanils should I make the files smaller?)

Also I added the missing background for default and contact (is the resolution okay)
Please choose one, maybe starting with photo plus graphic.

**Comment by ah-bas-und-aer** [comment]
Also the graphic element on the slider on „News“ is missing, can you add that?

**Comment by farzadgo** [comment]
dear @ah-bas-und-aer 
- the graphic on the slider of the news/homepage was already updated just needed to be merged. The SVG logo of NZN was used to do that in a different interval that the images. It functions like a mask.
- for the network member profile thumbnails, PNG files are choses, three variations are being assigned randomly for the members without profile image.
- the background _blank_ is for where?
- the architectural one (concrete) for the contact will be updated later.

**Comment by ah-bas-und-aer** [comment]
> the background _blank_ is for where?
the blank one was created incase you chould ad the graphic strokes mask here as well. You can ignore them.

**Comment by GuidaGG** [comment]
@ah-bas-und-aer  I added for now just one of the images as backgroung for kontakt, like it was on the design.
