### ISSUE TITLE
Arbeitsmaterialien

### ISSUE THREAD

**Issue by ah-bas-und-aer** [GuidaGG/NZN-frontend#133]
- [x] Can you add Nuumber and title on top of each "Arbeitsmaterial page"?
(Maybe also instead of this longer introductions. 
E.G. „1.1 How to Zwischennutzung“
I think this is nessecary for better orientation

Sidebar: 
- [x] Same here: The elements in the sidebar should contain title and author instead of an introduction.
- Also I would prefer to  leave the part in the sidebar with green background when its open, this can also help for sidebars in best practice and network.
- Furthermore in the sidebar a coloumn was planned that contains further links (vgl. XD-File) „Nützliche Links“, or did Svenja decided against it?
- [x] the hover effect of the button in the sidebar is strange, I would suggest to just delete the balck frame

**Comment by GuidaGG** [comment]
- Also I would prefer to leave the part in the sidebar with green background when its open, this can also help for sidebars in best practice and network.

maybe this is not possible within the timeframework. I will add it as  `good-to-have`

**Comment by GuidaGG** [comment]
# Same here: The elements in the sidebar should contain title and author instead of an introduction.

because we integrated the links into the sidebar, there are some elements that do not open a pdf on the side and therefore these need to keep the description on.
