### ISSUE TITLE
mobile genreal

### ISSUE THREAD

**Issue by ah-bas-und-aer** [GuidaGG/NZN-frontend#134]
- [ ] reduce “header“ hight
- [ ] i will ask if we can ignore the logos in the header, cause they are too small
- [x] reduce the spacing between the menu points in the menu

**Comment by ah-bas-und-aer** [comment]
For the mobile version there are too many font sizes, how do you want me to give you my suggestions for that? I can prefere and than call one of you or do you want me to type everything in here?

**Comment by GuidaGG** [comment]
> r the mobile version there are too many font sizes, how do you want me to give you my suggestions for that? I can prefere and

We use the same 4 from the desktop but in smaller version. Lets do this via videocall.

here our settings

```
// small screen
:root {
		--nzn-text-2xl: 40px;
		--nzn-text-xl: 24px;
		--nzn-text-base: 20px;
		--nzn-text-sm: 18px;
		--nzn-text-xs: 16px;
		--nzn-line-2xl: 47px;
		--nzn-line-xl: 30px;
		--nzn-line-base: 30px;
		--nzn-line-sm: 22px;
		--nzn-line-xs: 20px;
	}
        // > 1024px
	@screen lg {
		:root {
			--nzn-text-2xl: 72px;
			--nzn-text-xl: 40px;
			--nzn-text-base: 26px;
			--nzn-text-sm: 20px;
			--nzn-text-xs: 18px;
			--nzn-line-2xl: 67px;
			--nzn-line-xl: 50px;
			--nzn-line-base: 30px;
			--nzn-line-sm: 24px;
			--nzn-line-xs: 22px;
		}
	}
	// > 1800px
	@screen 3xl {
		:root {
			--nzn-text-2xl: 95px;
			--nzn-text-xl: 53px;
			--nzn-text-base: 35px;
			--nzn-text-sm: 20px;
			--nzn-text-xs: 18px;
			--nzn-line-2xl: 119px;
			--nzn-line-xl: 58px;
			--nzn-line-base: 45px;
			--nzn-line-sm: 24px;
			--nzn-line-xs: 22px;
		}
	}
	```

**Comment by ah-bas-und-aer** [comment]
> > r the mobile version there are too many font sizes, how do you want me to give you my suggestions for that? I can prefere and
> 
> We use the same 4 from the desktop but in smaller version. Lets do this via videocall.
> 
> here our settings
> 
> ```
> // small screen
> :root {
> 		--nzn-text-2xl: 40px;
> 		--nzn-text-xl: 24px;
> 		--nzn-text-base: 20px;
> 		--nzn-text-sm: 18px;
> 		--nzn-text-xs: 16px;
> 		--nzn-line-2xl: 47px;
> 		--nzn-line-xl: 30px;
> 		--nzn-line-base: 30px;
> 		--nzn-line-sm: 22px;
> 		--nzn-line-xs: 20px;
> 	}
>         // > 1024px
> 	@screen lg {
> 		:root {
> 			--nzn-text-2xl: 72px;
> 			--nzn-text-xl: 40px;
> 			--nzn-text-base: 26px;
> 			--nzn-text-sm: 20px;
> 			--nzn-text-xs: 18px;
> 			--nzn-line-2xl: 67px;
> 			--nzn-line-xl: 50px;
> 			--nzn-line-base: 30px;
> 			--nzn-line-sm: 24px;
> 			--nzn-line-xs: 22px;
> 		}
> 	}
> 	// > 1800px
> 	@screen 3xl {
> 		:root {
> 			--nzn-text-2xl: 95px;
> 			--nzn-text-xl: 53px;
> 			--nzn-text-base: 35px;
> 			--nzn-text-sm: 20px;
> 			--nzn-text-xs: 18px;
> 			--nzn-line-2xl: 119px;
> 			--nzn-line-xl: 58px;
> 			--nzn-line-base: 45px;
> 			--nzn-line-sm: 24px;
> 			--nzn-line-xs: 22px;
> 		}
> 	}
> 	```
> ```

Okay, when do you want to do this? This afternoon, tomorrow morning?

**Comment by GuidaGG** [comment]
I could do tomorrow morning.
We are now working more on vielfaeltig but I could take some time tomorrow for some NZN.
:) 
11am?

**Comment by ah-bas-und-aer** [comment]
> We are now working more on vielfaeltig but I could take some time tomorrow for some NZN.

Deal!

Bas&Aer Designstudio lädt Sie zu einem geplanten Zoom-Meeting ein.

Thema: Zoom meeting invitation - Zoom Meeting von Bas&Aer Designstudio – NZN Guida
Zeit: 25.Jan. 2024 11:00 AM Amsterdam, Berlin, Rom, Stockholm, Wien

Beitreten Zoom Meeting
https://us06web.zoom.us/j/89344808442?pwd=wEctSQwxrqhOQaTMbYCX74UTvyRM6K.1

Meeting-ID: 893 4480 8442
Kenncode: 187128

---

Schnelleinwahl mobil
+16892781000,,89344808442#,,,,*187128# Vereinigte Staaten
+17193594580,,89344808442#,,,,*187128# Vereinigte Staaten

---

Einwahl nach aktuellem Standort
• +1 689 278 1000 Vereinigte Staaten
• +1 719 359 4580 Vereinigte Staaten
• +1 720 707 2699 Vereinigte Staaten (Denver)
• +1 253 205 0468 Vereinigte Staaten
• +1 253 215 8782 Vereinigte Staaten (Tacoma)
• +1 301 715 8592 Vereinigte Staaten (Washington DC)
• +1 305 224 1968 Vereinigte Staaten
• +1 309 205 3325 Vereinigte Staaten
• +1 312 626 6799 Vereinigte Staaten (Chicago)
• +1 346 248 7799 Vereinigte Staaten (Houston)
• +1 360 209 5623 Vereinigte Staaten
• +1 386 347 5053 Vereinigte Staaten
• +1 507 473 4847 Vereinigte Staaten
• +1 564 217 2000 Vereinigte Staaten
• +1 646 558 8656 Vereinigte Staaten (New York)
• +1 646 931 3860 Vereinigte Staaten
• +1 669 444 9171 Vereinigte Staaten

Meeting-ID: 893 4480 8442
Kenncode: 187128

Ortseinwahl suchen: https://us06web.zoom.us/u/k3yg8voo6

**Comment by GuidaGG** [comment]
- `tracking-wider` on uppercase general, text-base mobile
